services:
  db:
    image: mysql:8
    container_name: ms_users_db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ms_users
      MYSQL_PASSWORD: ms_users
      MYSQL_USER: ms_users
      MYSQL_DATABASE: ms_users