spring:
    threads:
      virtual:
        enabled: true
    profiles:
      active: ${ENV:local}
    application:
        name: ms-users
    datasource:
      url: ${DATABASE_URL}
      username: ${DATABASE_USER}
      password: ${DATABASE_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: false
logging:
  file:
    name: logs/app.log
    path: logs
  level:
    root: INFO
    dev.carlosalbertojr: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"